=== shakeriamin21/cydetix/schemas/cyclonedx-1.7.schema.json
{
  "$id": "https://cydetix.dev/schemas/v1/cyclonedx-1.7.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "const": "https://cyclonedx.org/schema/bom-1.7.schema.json"
    },
    "bomFormat": {
      "type": "string",
      "const": "CycloneDX"
    },
    "specVersion": {
      "type": "string",
      "const": "1.7"
    },
    "serialNumber": {
      "type": "string",
      "pattern": "^urn:uuid:[0-9a-f-]{36}$"
    },
    "version": {
      "type": "integer",
      "exclusiveMinimum": 0,
      "maximum": 9007199254740991
    },
    "metadata": {
      "type": "object",
      "properties": {
        "timestamp": {
          "type": "string",
          "format": "date-time",
          "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$"
        },
        "tools": {
          "type": "object",
          "properties": {
            "components": {
              "minItems": 1,
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "application",
                      "library"
                    ]
                  },
                  "bom-ref": {
                    "type": "string",
                    "minLength": 1
                  },
                  "name": {
                    "type": "string",
                    "minLength": 1
                  },
                  "version": {
                    "type": "string",
                    "minLength": 1
                  },
                  "purl": {
                    "type": "string",
                    "pattern": "^pkg:"
                  },
                  "scope": {
                    "type": "string",
                    "enum": [
                      "required",
                      "optional",
                      "excluded"
                    ]
                  },
                  "properties": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string",
                          "minLength": 1
                        },
                        "value": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name",
                        "value"
                      ],
                      "additionalProperties": false
                    }
                  }
                },
                "required": [
                  "type",
                  "bom-ref",
                  "name",
                  "version",
                  "purl"
                ],
                "additionalProperties": false
              }
            }
          },
          "required": [
            "components"
          ],
          "additionalProperties": false
        },
        "component": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "application",
                "library"
              ]
            },
            "bom-ref": {
              "type": "string",
              "minLength": 1
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "version": {
              "type": "string",
              "minLength": 1
            },
            "purl": {
              "type": "string",
              "pattern": "^pkg:"
            },
            "scope": {
              "type": "string",
              "enum": [
                "required",
                "optional",
                "excluded"
              ]
            },
            "properties": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "minLength": 1
                  },
                  "value": {
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "value"
                ],
                "additionalProperties": false
              }
            }
          },
          "required": [
            "type",
            "bom-ref",
            "name",
            "version",
            "purl"
          ],
          "additionalProperties": false
        }
      },
      "required": [
        "timestamp",
        "tools"
      ],
      "additionalProperties": false
    },
    "components": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "application",
              "library"
            ]
          },
          "bom-ref": {
            "type": "string",
            "minLength": 1
          },
          "name": {
            "type": "string",
            "minLength": 1
          },
          "version": {
            "type": "string",
            "minLength": 1
          },
          "purl": {
            "type": "string",
            "pattern": "^pkg:"
          },
          "scope": {
            "type": "string",
            "enum": [
              "required",
              "optional",
              "excluded"
            ]
          },
          "properties": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "minLength": 1
                },
                "value": {
                  "type": "string"
                }
              },
              "required": [
                "name",
                "value"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "type",
          "bom-ref",
          "name",
          "version",
          "purl"
        ],
        "additionalProperties": false
      }
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "ref": {
            "type": "string",
            "minLength": 1
          },
          "dependsOn": {
            "type": "array",
            "items": {
              "type": "string",
              "minLength": 1
            }
          }
        },
        "required": [
          "ref",
          "dependsOn"
        ],
        "additionalProperties": false
      }
    },
    "compositions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "aggregate": {
            "type": "string",
            "enum": [
              "complete",
              "incomplete",
              "unknown"
            ]
          },
          "assemblies": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "aggregate",
          "assemblies"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "$schema",
    "bomFormat",
    "specVersion",
    "serialNumber",
    "version",
    "metadata",
    "components",
    "dependencies",
    "compositions"
  ],
  "additionalProperties": false
}

=== shakeriamin21/cydetix/validation/alpha12/cydetix.cdx.json
{
  "$schema": "https://cyclonedx.org/schema/bom-1.7.schema.json",
  "bomFormat": "CycloneDX",
  "specVersion": "1.7",
  "serialNumber": "urn:uuid:d5a8b698-805c-59d4-ad1d-bf6632119669",
  "version": 1,
  "metadata": {
    "timestamp": "2026-09-13T08:04:22.205Z",
    "tools": {
      "components": [
        {
          "type": "application",
          "bom-ref": "pkg:npm/cydetix@0.6.0-alpha.12",
          "name": "cydetix",
          "version": "0.6.0-alpha.12",
          "purl": "pkg:npm/cydetix@0.6.0-alpha.12"
        }
      ]
    },
    "component": {
      "type": "application",
      "bom-ref": "pkg:npm/cydetix@0.6.0-alpha.12",
      "name": "cydetix",
      "version": "0.6.0-alpha.12",
      "purl": "pkg:npm/cydetix@0.6.0-alpha.12"
    }
  },
  "components": [
    {
      "type": "library",
      "bom-ref": "pkg:npm/%40babel/code-frame@8.0.0",
      "name": "@babel/code-frame",
      "version": "8.0.0",
      "purl": "pkg:npm/%40babel/code-frame@8.0.0",
      "scope": "required",
      "properties": [
        {
          "name": "cydetix:dependency-kind",
          "value": "transitive"
        },
        {
          "name": "cydetix:resolved",
          "value": "true"
        },
        {
          "name": "cydetix:source",
          "value": "registry"
        }
      ]
    },
    {
      "type": "library",
      "bom-ref": "pkg:npm/%40babel/generator@8.0.0",
      "name": "@babel/generator",
      "version": "8.0.0",
      "purl": "pkg:npm/%40babel/generator@8.0.0",
      "scope": "required",
      "properties": [
        {
          "name": "cydetix:dependency-kind",
          "value": "transitive"
        },
        {
          "name": "cydetix:resolved",
          "value": "true"
        },
        {
          "name": "cydetix:source",
          "value": "registry"
        }
      ]
    },
    {
      "type": "library",
      "bom-ref": "pkg:npm/%40babel/helper-globals@8.0.0",
      "name": "@babel/helper-globals",
      "version": "8.0.0",
      "purl": "pkg:npm/%40babel/helper-globals@8.0.0",
      "scope": "required",
      "properties": [
        {
          "name": "cydetix:dependency-kind",
          "value": "transitive"
        },
        {
          "name": "cydetix:resolved",
          "value": "true"
        },
        {
          "name": "cydetix:source",
          "value": "registry"
        }
      ]
    },
    {
      "type": "library",
      "bom-ref": "pkg:npm/%40babel/helper-string-parser@7.29.7",
      "name": "@babel/helper-string-parser",
      "version": "7.29.7",
      "purl": "pkg:npm/%40babel/helper-string-parser@7.29.7",
      "scope": "required",
      "properties": [
        {
          "name": "cydetix:dependency-kind",
          "value": "transitive"
        },
        {
          "name": "cydetix:resolved",
          "value": "true"
        },
        {
          "name": "cydetix:source",
          "value": "registry"
        }
      ]
    },
    {
      "type": "library",
      "bom-ref": "pkg:npm/%40babel/helper-string-parser@8.0.0",
      "name": "@babel/helper-string-parser",
      "version": "8.0.0",
      "purl": "pkg:npm/%40babel/helper-string-parser@8.0.0",
      "scope": "required",
      "properties": [
        {
          "name": "cydetix:dependency-kind",
          "value": "transitive"
        },
        {
          "name": "cydetix:resolved",
          "value": "true"
        },
        {
          "name": "cydetix:source",
          "value": "registry"
        }
      ]
    },
    {
      "type": "library",
      "bom-ref": "pkg:npm/%40babel/helper-validator-identifier@7.29.7",
      "name": "@babel/helper-validator-identifier",
      "version": "7.29.7",
      "purl": "pkg:npm/%40babel/helper-validator-identifier@7.29.7",
      "scope": "required",
      "properties": [
        {
          "name": "cydetix:dependency-kind",
          "value": "transitive"
        },
        {
          "name": "cydetix:resolved",
          "value": "true"
        },
        {
          "name": "cydetix:source",
          "value": "registry"
        }
      ]
    },
    {
      "type": "library",
      "bom-ref": "pkg:npm/%40babel/helper-validator-identifier@8.0.4",
      "name": "@babel/helper-validator-identifier",
      "version": "8.0.4",
      "purl": "pkg:npm/%40babel/helper-validator-identifier@8.0.4",
      "scope": "required",
      "properties": [
        {
          "name": "cydetix:dependency-kind",
          "value": "transitive"
        },
        {
          "name": "cydetix:resolved",
          "value": "true"
        },
        {
          "name": "cydetix:source",
          "value": "registry"
        }
      ]
    },
    {
      "type": "library",
      "bom-ref": "pkg:npm/%40babel/parser@8.0.4",
      "name": "@babel/parser",
      "version": "8.0.4",
      "purl": "pkg:npm/%40babel/parser@8.0.4",
      "scope": "required",
      "properties": [
        {
          "name": "cydetix:dependency-kind",
          "value": "direct"
        },
        {
          "name": "cydetix:resolved",
          "value": "true"
        },
        {
          "name": "cydetix:source",
          "value": "registry"
        }
      ]
    },
    {
      "type": "library",
      "bom-ref": "pkg:npm/%40babel/template@8.0.0",
      "name": "@babel/template",
      "version": "8.0.0",
      "purl": "pkg:npm/%40babel/template@8.0.0",
      "scope": "required",
      "properties": [
        {
          "name": "cydetix:dependency-kind",
          "value": "transitive"
        },
        {
          "name": "cydetix:resolved",
          "value": "true"
        },
        {
          "name": "cydetix:source",
          "value": "registry"
        }
      ]
    },
    {
      "type": "library",
      "bom-ref": "pkg:npm/%40babel/traverse@8.0.4",
      "name": "@babel/traverse",
      "version": "8.0.4",
      "purl": "pkg:npm/%40babel/traverse@8.0.4",
      "scope": "required",
      "properties": [
        {
          "name": "cydetix:dependency-kind",
          "value": "direct"
        },
        {
          "name": "cydetix:resolved",
          "value": "true"
        },
        {
          "name": "cydetix:source",
          "value": "registry"
        }
      ]
    },
    {
      "type": "library",
      "bom-ref": "pkg:npm/%40babel/types@7.29.8",
      "name": "@babel/types",
      "version": "7.29.8",
      "purl": "pkg:npm/%40babel/types@7.29.8",
      "scope": "required",
      "properties": [
        {
          "name": "cydetix:dependency-kind",
          "value": "transitive"
        },
        {
          "name": "cydetix:resolved",
          "value": "true"
        },
        {
          "name": "cydetix:source",
          "value": "registry"
        }
      ]
    },
    {
      "type": "library",
      "bom-ref": "pkg:npm/%40babel/types@8.0.4",
      "name": "@babel/types",
      "version": "8.0.4",
      "purl": "pkg:npm/%40babel/types@8.0.4",
      "scope": "required",
      "properties": [
        {
          "name": "cydetix:dependency-kind",
          "value": "direct"
        },
        {
          "name": "cydetix:resolved",
          "value": "true"
        },
        {
          "name": "cydetix:source",
          "value": "registry"
        }
      ]
    },
    {
      "type": "library",
      "bom-ref": "pkg:npm/%40esbuild/aix-ppc64@0.28.2",
      "name": "@esbuild/aix-ppc64",
      "version": "0.28.2",
      "purl": "pkg:npm/%40esbuild/aix-ppc64@0.28.2",
      "scope": "optional",
      "properties": [
        {
          "name": "cydetix:dependency-kind",
          "value": "transitive"
        },
        {
          "name": "cydetix:resolved",
          "value": "true"
        },
        {
          "name": "cydetix:source",
          "value": "registry"
        }
      ]
    },
    {
      "type": "library",
      "bom-ref": "pkg:npm/%40esbuild/android-arm@0.28.2",
      "name": "@esbuild/android-arm",
      "version": "0.28.2",
      "purl": "pkg:npm/%40esbuild/android-arm@0.28.2",
      "scope": "optional",
      "properties": [
        {
          "name": "cydetix:dependency-kind",
          "value": "transitive"
        },
        {
          "name": "cydetix:resolved",
          "value": "true"
        },
        {
          "name": "cydetix:source",
          "value": "registry"
        }
      ]
    },
    {
      "type": "library",
      "bom-ref": "pkg:npm/%40esbuild/android-arm64@0.28.2",
      "name": "@esbuild/android-arm64",
      "version": "0.28.2",
      "purl": "pkg:npm/%40esbuild/android-arm64@0.28.2",
      "scope": "optional",
      "properties": [
        {
          "name": "cydetix:dependency-kind",
          "value": "transitive"
        },
        {
          "name": "cydetix:resolved",
          "value": "true"
        },
        {
          "name": "cydetix:source",
          "value": "registry"
        }
      ]
    },
    {
      "type": "library",
      "bom-ref": "pkg:npm/%40esbuild/android-x64@0.28.2",
      "name": "@esbuild/android-x64",
      "version": "0.28.2",
      "purl": "pkg:npm/%40esbuild/android-x64@0.28.2",
      "scope": "optional",
      "properties": [
        {
          "name": "cydetix:dependency-kind",
          "value": "transitive"
        },
        {
          "name": "cydetix:resolved",
          "value": "true"
        },
        {
          "name": "cydetix:source",
          "value": "registry"
        }
      ]
    },
    {
      "type": "library",
      "bom-ref": "pkg:npm/%40esbuild/darwin-arm64@0.28.2",
      "name": "@esbuild/darwin-arm64",
      "version": "0.28.2",
      "purl": "pkg:npm/%40esbuild/darwin-arm64@0.28.2",
      "scope": "optional",
      "properties": [
        {
          "name": "cydetix:dependency-kind",
          "value": "transitive"
        },
        {
          "name": "cydetix:resolved",
          "value": "true"
        },
        {
          "name": "cydetix:source",
          "value": "registry"
        }
      ]
    },
    {
      "type": "library",
